site_name: Polygenic Risk Score (PRS) Tutorial
site_url: https://github.com/nmoragas/PRS_tutorial
site_author: you
site_description: a short description of your website

nav:
  - About: index.md

theme: 
    name: readthedocs
    highlightjs: false

css: style.css
