site_name: Polygenic Risk Score (PRS) Tutorial
site_url: https://github.com/nmoragas/PRS_tutorial
site_author: Núria Moragas Garcia

nav:
  - About: index.md

theme: 
    name: readthedocs
    highlightjs: false

extra_css: 
  - style.css
